build: off
version: '{build}'
shallow_clone: true
skip_tags: true

environment:
  matrix:
    - nodejs_version: '5'
    - nodejs_version: '0.12'
    - nodejs_version: '0.10'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm -g install npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install

matrix:
  fast_finish: true

test_script:
  - node --version
  - npm --version
  - npm test
